#
# configuration for serial recording daemon to save logs/telemetry over ttyS3/S4
#
# add in your /etc/luckfox.cfg lines to enable one or another serials like
# UART3_M1_STATUS=1
# or
# UART4_M1_STATUS=1

# Location of files to save
RECORDER_FOLDER=/userdata/recordings
RECORDER_FILE="recorder.log"
RECORDER_FILE_TAG="@"   # all lines strated with @filename@contents will be stored in $RECORDER_FOLDER/filename

# Serial to use, and options to stty as called before reading, must be in sync to another side
SERIAL_DEVICE=/dev/ttyS3
# this one works fine for 10 cm lane
SERIAL_OPTIONS="921600 cs8 -parenb -cstopb -ixon"
# safe options are
#SERIAL_OPTIONS="115200 cs8 -parenb -cstopb -ixon"
