#
# configuration for camera writing daemon
#

# Location of files to save
VIDEO_FOLDER=/userdata/videos

# Video format and general parameters
VIDEO_FORMAT=mjpeg  # h264 and h265 supported but required FHD or less
VIDEO_WIDTH=2304
VIDEO_HEIGH=1296
VIDEO_DURATION=$((15 * 60))
VIDEO_FPS=30

# LED for blinking
_LED_HOME=/sys/class/leds/work
LED_CONTROL="$_LED_HOME/trigger"    # none vs. activity vs. mmc1
LED_VALUE="$_LED_HOME/brightness"   # 0 - off, 1 - on

# thermal tracking (soc used)
THERMAL=/sys/devices/virtual/thermal/thermal_zone0/temp

# some inputs for PC is there or not
ANDROID_USB_STATE=/sys/class/android_usb/android0/state     # if CONFIGURED => PC connected
CARRIER_USB_STATE=/sys/class/net/usb0/carrier               # 1 => connected


# nice place for common functions
function loggy() {
    logger -s -t camerad "$@"
}

function led_control() {
    local mode="$1"
    local value="$2"

    [ -f "$LED_CONTROL" ] && echo -n "$mode" > $LED_CONTROL
    [ -f "$LED_VALUE" ] && [ -n "$value" ] && echo -n "$value" > $LED_VALUE
}

