#!/usr/bin/env python3
# tools/gen_graph.py — architecture views for doc/architecture.md, generated by PARSING the on-device
# sources (stdlib `ast`; never imports them, so machine/esp32/network being absent on the host is fine,
# and no third-party tool is needed). Three views + one analysis:
#   1. Module dependency graph — who imports whom, layered (leaves first), + a fan-in/fan-out table.
#   2. Class hierarchy — base -> subclasses across modules (the task.Task fleet, driver/mixin bases).
#   3. Flight-control HOT PATH — the call tree from Flight._step() (the 100 Hz, GC-off control step),
#      resolved across objects (self._x is typed from `self._x = module.Class(...)`), with per-function
#      FLAGS for the patterns that hurt a GC-off real-time loop: heap allocations (dict/list/set/tuple
#      literals, comprehensions, f-strings, %-format, .items/.values/.keys), float trig (math.sin/cos/
#      atan2/sqrt/...), and dynamic lookups (.find/.get/.active/.parameter). This is the findings-style
#      "analyse the stack to find deep problems" pass — the flags are CANDIDATES to review, not verdicts.
#
#   python3 tools/gen_graph.py            # writes doc/architecture.md
#   python3 tools/gen_graph.py --check    # exit 1 if doc/architecture.md is stale (CI gate)

import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLIDER_DIRS = ['src/glider', 'src/glider/drivers', 'src/glider/tasks']
SKIP_PREFIXES = ('test_', 'itest_', 'bench_', '__init__', 'version', 'example_', 'gen_')
HOT_ENTRY = ('flight', 'Flight', '_step')  # the 100 Hz control step -> the hot-path trace root
MAX_DEPTH = 8

_TRIG = frozenset(('sin', 'cos', 'tan', 'atan2', 'atan', 'asin', 'acos', 'sqrt', 'isqrt',
                   'radians', 'degrees', 'hypot', 'pow', 'exp', 'log'))
_LOOKUP = frozenset(('find', 'active', 'parameter', 'get'))  # dynamic hardware / dict lookups
_ALLOC_METHODS = frozenset(('items', 'values', 'keys', 'format', 'copy', 'split', 'join'))


class Module:
    """One parsed on-device module: its import aliases, module-level functions, and classes (with the
    inferred type of each `self._x` attribute so cross-object calls resolve)."""

    def __init__(self, name, path, kind):
        self.name = name
        self.path = path
        self.kind = kind
        self.import_alias = {}   # local alias -> our module name (import X / import X as Y)
        self.from_import = {}    # imported symbol -> its module (from X import a)
        self.funcs = {}          # module-level function name -> node
        self.classes = {}        # class name -> {'bases': [str], 'methods': {name: node}, 'attrs': {a: (mod, cls)}}


def _iter_sources():
    for rel in GLIDER_DIRS:
        directory = os.path.join(ROOT, rel)
        for name in sorted(os.listdir(directory)):
            if name.endswith('.py') and not name.startswith(SKIP_PREFIXES) \
                    and not os.path.islink(os.path.join(directory, name)):
                yield rel, name, os.path.join(directory, name)


def _attr_type(value, module):
    """(module, class) a call expression constructs, e.g. `governor.Governor(...)` -> ('governor',
    'Governor') and a same-module `Pid(...)` -> (this module, 'Pid'); else None."""
    if not isinstance(value, ast.Call):
        return None
    func = value.func
    if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name):
        mod = module.import_alias.get(func.value.id)
        if mod is not None:
            return (mod, func.attr)
    elif isinstance(func, ast.Name) and func.id in module.classes:
        return (module.name, func.id)
    return None


def _collect_attrs(class_node, module, attrs):
    """Record `self._x = module.Class(...)` assignments anywhere in the class so the hot-path trace can
    resolve `self._x.method()` across objects (Flight builds its collaborators in setup(), not __init__)."""
    for node in ast.walk(class_node):
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name) \
                    and target.value.id == 'self':
                typed = _attr_type(node.value, module)
                if typed is not None:
                    attrs[target.attr] = typed


def parse_modules():
    """Parse every on-device module into a Module (imports, functions, classes + attribute types)."""
    modules = {}
    for rel, name, path in _iter_sources():
        modname = name[:-3]
        kind = 'task' if rel.endswith('tasks') else ('driver' if rel.endswith('drivers') else 'core')
        module = Module(modname, path, kind)
        with open(path) as handle:
            tree = ast.parse(handle.read())
        for node in tree.body:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module.import_alias[alias.asname or alias.name] = alias.name
            elif isinstance(node, ast.ImportFrom) and node.module:
                for alias in node.names:
                    module.from_import[alias.asname or alias.name] = node.module
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                module.funcs[node.name] = node
            elif isinstance(node, ast.ClassDef):
                methods = {m.name: m for m in node.body
                           if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))}
                attrs = {}
                _collect_attrs(node, module, attrs)
                module.classes[node.name] = {'bases': [ast.unparse(b) for b in node.bases],
                                             'methods': methods, 'attrs': attrs}
        modules[modname] = module
    return modules


# ---------- view 1: module dependency graph ----------

def module_deps(modules):
    """{module: set(of OUR modules it imports}} — external/stdlib imports dropped."""
    ours = set(modules)
    deps = {}
    for name, module in modules.items():
        used = set(module.import_alias.values()) | set(module.from_import.values())
        deps[name] = {u for u in used if u in ours and u != name}
    return deps


def _layers(deps):
    """Topological layering: layer 0 = modules that import no OUR module (leaves), then up. A module in
    a cycle lands one above its lowest already-placed dependency (cycles are reported, not crashed)."""
    layer = {}
    remaining = dict(deps)
    current = 0
    while remaining:
        ready = [m for m, d in remaining.items() if all(x in layer for x in d)]
        if not ready:  # a cycle -> place the rest at the current layer and stop refining
            for m in remaining:
                layer[m] = current
            break
        for m in ready:
            layer[m] = current
            del remaining[m]
        current += 1
    return layer


def render_module_graph(modules, out):
    deps = module_deps(modules)
    layer = _layers(deps)
    rdeps = {m: [] for m in modules}
    for m, ds in deps.items():
        for d in ds:
            rdeps[d].append(m)
    out.append('## Module dependency graph\n')
    out.append('On-device modules layered leaves-first (a module depends only on lower layers, barring '
               'cycles). `->` lists the OUR-modules it imports.\n')
    by_layer = {}
    for m, level in layer.items():
        by_layer.setdefault(level, []).append(m)
    for level in sorted(by_layer):
        out.append('**Layer %d**\n' % level)
        for m in sorted(by_layer[level]):
            imports = ', '.join('`%s`' % d for d in sorted(deps[m]))
            out.append('- `%s` (%s)%s' % (m, modules[m].kind, ' -> ' + imports if imports else ''))
        out.append('')
    hubs = sorted(modules, key=lambda m: len(rdeps[m]), reverse=True)[:8]
    out.append('**Most depended-on (fan-in)** — a change here ripples widest:\n')
    for m in hubs:
        if rdeps[m]:
            out.append('- `%s` — imported by %d: %s'
                       % (m, len(rdeps[m]), ', '.join('`%s`' % x for x in sorted(rdeps[m]))))
    out.append('')
    cycles = [m for m, level in layer.items()
              if any(layer.get(d, 0) >= level for d in deps[m])]
    if cycles:
        out.append('**Import cycles detected** (unresolved layering): %s\n'
                   % ', '.join('`%s`' % c for c in sorted(cycles)))


# ---------- view 2: class hierarchy ----------

def render_class_hierarchy(modules, out):
    children = {}  # base class simple-name -> [(module, class)]
    all_classes = {}
    for module in modules.values():
        for cls, info in module.classes.items():
            all_classes[cls] = module.name
            for base in info['bases']:
                simple = base.split('.')[-1]
                children.setdefault(simple, []).append((module.name, cls))
    out.append('## Class hierarchy\n')
    out.append('Base class -> the on-device classes that extend it (the base may be an external one, '
               'e.g. `task.Task`).\n')
    for base in sorted(children):
        kids = sorted(children[base])
        out.append('- **`%s`** <- %s' % (base, ', '.join('`%s.%s`' % (m, c) for m, c in kids)))
    out.append('')


# ---------- view 3: hot-path call trace + analysis ----------

def _flags(node):
    """Per-function GC-off risk flags: heap allocations, float trig, and dynamic lookups."""
    allocs, trig, lookups = [], [], []
    for sub in ast.walk(node):
        if isinstance(sub, (ast.Dict, ast.Set, ast.DictComp, ast.SetComp, ast.ListComp,
                            ast.GeneratorExp, ast.JoinedStr)):
            allocs.append(type(sub).__name__)
        elif isinstance(sub, (ast.List,)) and sub.elts:
            allocs.append('List')
        elif isinstance(sub, ast.Tuple) and isinstance(sub.ctx, ast.Load) and len(sub.elts) > 1:
            allocs.append('Tuple')  # a Load-context tuple literal/return allocates (unpack targets do not)
        elif isinstance(sub, ast.BinOp) and isinstance(sub.op, ast.Mod) \
                and isinstance(sub.left, ast.Constant) and isinstance(sub.left.value, str):
            allocs.append("'%'-format")
        elif isinstance(sub, ast.Call) and isinstance(sub.func, ast.Attribute):
            attr = sub.func.attr
            if attr in _ALLOC_METHODS:
                allocs.append('.' + attr + '()')
            if attr in _TRIG and _root_name(sub.func.value) == 'math':
                trig.append('math.' + attr)
            if attr in _LOOKUP:
                lookups.append('.' + attr + '()')
    return {'alloc': _tally(allocs), 'trig': _tally(trig), 'lookup': _tally(lookups)}


def _tally(items):
    counts = {}
    for item in items:
        counts[item] = counts.get(item, 0) + 1
    return ', '.join('%s x%d' % (k, v) if v > 1 else k for k, v in sorted(counts.items()))


def _root_name(node):
    return node.id if isinstance(node, ast.Name) else None


def _resolve(call, module, cls, modules):
    """Best-effort (target_module, 'Class.method' or 'func') for a Call, or None. Resolves self.method
    (same class), self._x.method (typed attribute), module.func, and bare module-level / from-imported
    functions. Typed-attribute chains it cannot type (self._pid[a].reset()) stay unresolved."""
    func = call.func
    if isinstance(func, ast.Attribute):
        value = func.value
        if isinstance(value, ast.Name) and value.id == 'self' and cls is not None:
            if func.attr in modules[module.name].classes[cls]['methods']:
                return (module.name, '%s.%s' % (cls, func.attr))
        elif isinstance(value, ast.Attribute) and isinstance(value.value, ast.Name) \
                and value.value.id == 'self' and cls is not None:
            typed = modules[module.name].classes[cls]['attrs'].get(value.attr)
            if typed is not None:
                mod, target_cls = typed
                if mod in modules and target_cls in modules[mod].classes \
                        and func.attr in modules[mod].classes[target_cls]['methods']:
                    return (mod, '%s.%s' % (target_cls, func.attr))
        elif isinstance(value, ast.Name):
            mod = module.import_alias.get(value.id)
            if mod in modules and func.attr in modules[mod].funcs:
                return (mod, func.attr)
    elif isinstance(func, ast.Name):
        if func.id in module.funcs:
            return (module.name, func.id)
        mod = module.from_import.get(func.id)
        if mod in modules and func.id in modules[mod].funcs:
            return (mod, func.id)
    return None


def _node_for(modules, module_name, qualname):
    module = modules[module_name]
    if '.' in qualname:
        cls, method = qualname.split('.', 1)
        return cls, module.classes[cls]['methods'].get(method)
    return None, module.funcs.get(qualname)


def trace_hot_path(modules, out):
    out.append('## Flight-control hot path — `Flight._step()` (100 Hz, GC-off)\n')
    out.append('The resolved call tree from the control step, with GC-off risk flags per function '
               '(⚠alloc = heap literal/format, ∿trig = float trig, ⌕lookup = dynamic find/get). '
               'Cross-object calls are resolved via each `self._x`\'s constructed type; a leaf with no '
               'children is either a resolved primitive or a call this static pass could not type.\n')
    seen = set()
    flagged = []
    flagged_keys = set()

    def walk(module_name, qualname, depth):
        key = (module_name, qualname)
        cls, node = _node_for(modules, module_name, qualname)
        marker = ''
        if node is not None:
            f = _flags(node)
            bits = []
            if f['alloc']:
                bits.append('⚠' + f['alloc'])
            if f['trig']:
                bits.append('∿' + f['trig'])
            if f['lookup']:
                bits.append('⌕' + f['lookup'])
            if bits:
                marker = '  — ' + '; '.join(bits)
                if key not in flagged_keys:  # one entry per function, not per reachability path
                    flagged_keys.add(key)
                    flagged.append((module_name, qualname, bits))
        out.append('%s- `%s.%s`%s%s' % ('  ' * depth, module_name, qualname, marker,
                                        ' …' if key in seen else ''))
        if key in seen or node is None or depth >= MAX_DEPTH:
            return
        seen.add(key)
        targets = []
        for sub in ast.walk(node):
            if isinstance(sub, ast.Call):
                resolved = _resolve(sub, modules[module_name], cls, modules)
                if resolved is not None and resolved not in targets:
                    targets.append(resolved)
        for tmod, tqual in targets:
            walk(tmod, tqual, depth + 1)

    walk(HOT_ENTRY[0], '%s.%s' % (HOT_ENTRY[1], HOT_ENTRY[2]), 0)
    out.append('')
    out.append('### Hot-path analysis — functions carrying GC-off risk flags\n')
    out.append('Candidates to review (a flag in a GC-off 100 Hz path is a per-step heap-churn / cost '
               'risk — many are already deliberate/cold-branch; this pass surfaces them, it does not '
               'judge). Empty = the traced path is clean.\n')
    if not flagged:
        out.append('_None flagged in the resolved hot path._\n')
    else:
        for module_name, qualname, bits in flagged:
            out.append('- `%s.%s` — %s' % (module_name, qualname, '; '.join(bits)))
        out.append('')


def build():
    modules = parse_modules()
    out = ['# Coludo architecture', '',
           '_Generated by `tools/gen_graph.py` (static AST parse — never imports) — do not edit by hand; '
           'run `python3 tools/gen_graph.py`. Companion to the per-module `api.md`._', '']
    render_module_graph(modules, out)
    render_class_hierarchy(modules, out)
    trace_hot_path(modules, out)
    return '\n'.join(out).rstrip() + '\n'


def main():
    target = os.path.join(ROOT, 'doc', 'architecture.md')
    content = build()
    if '--check' in sys.argv:
        current = open(target).read() if os.path.exists(target) else ''
        if current != content:
            print('doc/architecture.md is STALE — run: python3 tools/gen_graph.py')
            sys.exit(1)
        print('doc/architecture.md is up to date')
        return
    with open(target, 'w') as handle:
        handle.write(content)
    print('wrote %s' % target)


if __name__ == '__main__':
    main()
